# Generated by Django 4.1.6 on 2023-05-08 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import quiz.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
                ('image', models.ImageField(blank=True, null=True, upload_to=quiz.models.Science.scienceImage)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='quiz.science')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(verbose_name='Mavzu')),
                ('science', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='science', to='quiz.science')),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='quiz.section')),
            ],
        ),
        migrations.CreateModel(
            name='Solved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answers', models.TextField()),
                ('result', models.CharField(blank=True, max_length=555, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('science', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.science')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.subject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('akam_id', models.IntegerField(null=True)),
                ('question_name', models.TextField(blank=True, verbose_name='Savol')),
                ('question_image', models.ImageField(blank=True, null=True, upload_to=quiz.models.Quiz.nameFile, verbose_name='Rasmli savol:')),
                ('var_a_name', models.CharField(blank=True, max_length=555, null=True, verbose_name='A:')),
                ('var_a_image', models.ImageField(blank=True, null=True, upload_to=quiz.models.Quiz.answerFile)),
                ('var_a_id', models.IntegerField()),
                ('var_b_name', models.CharField(blank=True, max_length=555, null=True, verbose_name='B:')),
                ('var_b_image', models.ImageField(blank=True, null=True, upload_to=quiz.models.Quiz.answerFile)),
                ('var_b_id', models.IntegerField()),
                ('var_c_name', models.CharField(blank=True, max_length=555, null=True, verbose_name='C:')),
                ('var_c_image', models.ImageField(blank=True, null=True, upload_to=quiz.models.Quiz.answerFile)),
                ('var_c_id', models.IntegerField(blank=True)),
                ('var_d_name', models.CharField(blank=True, max_length=555, null=True, verbose_name='D:')),
                ('var_d_image', models.ImageField(blank=True, null=True, upload_to=quiz.models.Quiz.answerFile)),
                ('var_d_id', models.IntegerField(blank=True)),
                ('correct', models.IntegerField()),
                ('owner', models.IntegerField(blank=True, null=True)),
                ('science', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.science')),
                ('subject', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.subject')),
            ],
        ),
    ]
