# Generated by Django 4.1.5 on 2023-02-11 10:28

from django.db import migrations, models
import django.db.models.deletion
import quiz.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('science', models.IntegerField(blank=True, null=True)),
                ('subject_id', models.IntegerField(blank=True, null=True)),
                ('akam_id', models.IntegerField(null=True)),
                ('question_name', models.TextField(verbose_name='Savol')),
                ('question_image', models.ImageField(null=True, upload_to=quiz.models.Quiz.nameFile, verbose_name='Subject Image:')),
                ('var_a_name', models.CharField(max_length=555, verbose_name='A:')),
                ('var_a_id', models.IntegerField()),
                ('var_b_name', models.CharField(max_length=555, verbose_name='B:')),
                ('var_b_id', models.IntegerField()),
                ('var_c_name', models.CharField(blank=True, max_length=555, verbose_name='C:')),
                ('var_c_id', models.IntegerField(blank=True)),
                ('var_d_name', models.CharField(blank=True, max_length=555, verbose_name='D:')),
                ('var_d_id', models.IntegerField(blank=True)),
                ('correct', models.IntegerField()),
                ('owner', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Science',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=55)),
            ],
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='quiz.science')),
            ],
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.TextField(verbose_name='Mavzu')),
                ('science', models.IntegerField(null=True)),
                ('section', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='quiz.section')),
            ],
        ),
    ]
