# Generated by Django 4.1.6 on 2023-02-13 10:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='science',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='science', to='quiz.science'),
        ),
    ]
