# Generated by Django 4.1.6 on 2023-02-18 13:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_alter_subject_science'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='science',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='section', to='quiz.science'),
        ),
    ]
