# Generated by Django 4.1.5 on 2023-02-06 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_quiz_delete_subjectquiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='subject_grade',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
