# Generated by Django 4.1.6 on 2023-02-18 15:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_alter_section_science'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='subject_id',
        ),
        migrations.AddField(
            model_name='quiz',
            name='subject',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.subject'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='science',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='quiz.science'),
        ),
    ]
