# Generated by Django 4.1.5 on 2023-02-06 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0003_subject_subject_grade'),
    ]

    operations = [
        migrations.AddField(
            model_name='science',
            name='section',
            field=models.CharField(max_length=55, null=True),
        ),
    ]
