# Generated by Django 4.1.5 on 2023-02-06 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0004_science_section'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='science_id',
        ),
    ]
