# Generated by Django 4.1.5 on 2023-02-09 10:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_remove_quiz_science_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='science_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='science', to='quiz.science'),
        ),
    ]
