# Generated by Django 4.1.6 on 2023-05-03 14:58

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0005_alter_subject_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='var_a_image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.Quiz.answerFile),
        ),
        migrations.AddField(
            model_name='quiz',
            name='var_b_image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.Quiz.answerFile),
        ),
        migrations.AddField(
            model_name='quiz',
            name='var_c_image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.Quiz.answerFile),
        ),
        migrations.AddField(
            model_name='quiz',
            name='var_d_image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.Quiz.answerFile),
        ),
        migrations.AddField(
            model_name='science',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.Science.scienceImage),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.Quiz.nameFile, verbose_name='Subject Image:'),
        ),
    ]
