# Generated by Django 4.1.5 on 2023-02-10 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_alter_subject_science_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='science',
            name='section',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='science_id',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='subject_grade',
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='quiz.science')),
            ],
        ),
        migrations.AddField(
            model_name='subject',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='quiz.section'),
        ),
    ]
