# Generated by Django 4.1.6 on 2023-05-03 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0006_quiz_var_a_image_quiz_var_b_image_quiz_var_c_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='var_c_name',
            field=models.CharField(blank=True, max_length=555, null=True, verbose_name='C:'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='var_d_name',
            field=models.CharField(blank=True, max_length=555, null=True, verbose_name='D:'),
        ),
    ]
