# Generated by Django 4.1.5 on 2023-02-10 11:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0007_remove_science_section_remove_subject_science_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='science',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sciences', to='quiz.science'),
        ),
    ]
