# Generated by Django 4.1.5 on 2023-02-10 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_alter_section_science'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='science',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='section',
            name='science',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='quiz.science'),
        ),
        migrations.AlterField(
            model_name='subject',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subjects', to='quiz.section'),
        ),
    ]
