# Generated by Django 4.1.6 on 2023-05-07 06:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0008_solved'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='section',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='section', to='quiz.section'),
        ),
    ]
