# Generated by Django 4.1.6 on 2023-05-07 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_alter_subject_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='science',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='science', to='quiz.science'),
        ),
    ]
