# Generated by Django 4.1.5 on 2023-02-10 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0009_subject_science_alter_section_science_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subject',
            name='science',
            field=models.IntegerField(null=True),
        ),
    ]
