# Generated by Django 4.1.6 on 2023-05-07 11:02

from django.db import migrations, models
import quiz.models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_subject_science'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quiz',
            name='question_image',
            field=models.ImageField(blank=True, null=True, upload_to=quiz.models.Quiz.nameFile, verbose_name='Rasmli savol:'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='question_name',
            field=models.TextField(blank=True, verbose_name='Savol'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='var_a_name',
            field=models.CharField(blank=True, max_length=555, null=True, verbose_name='A:'),
        ),
        migrations.AlterField(
            model_name='quiz',
            name='var_b_name',
            field=models.CharField(blank=True, max_length=555, null=True, verbose_name='B:'),
        ),
    ]
