# Generated by Django 4.1.5 on 2023-02-10 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0010_alter_subject_science'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='akam_id',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='quiz',
            name='science',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
