# Generated by Django 4.1.5 on 2023-02-11 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='University',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=400)),
                ('description', models.CharField(blank=True, max_length=800)),
                ('image', models.CharField(blank=True, max_length=300)),
                ('map', models.CharField(blank=True, max_length=800)),
                ('phone', models.CharField(blank=True, max_length=20)),
                ('address', models.CharField(blank=True, max_length=255)),
                ('keywords', models.CharField(blank=True, max_length=800)),
                ('profession', models.CharField(blank=True, max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Study',
            fields=[
                ('id', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('study_name', models.CharField(max_length=400)),
                ('science_1', models.CharField(max_length=55)),
                ('science_2', models.CharField(max_length=55)),
                ('grant_ball', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('contract_ball', models.DecimalField(blank=True, decimal_places=1, max_digits=3)),
                ('grant_count', models.IntegerField(blank=True, default=0)),
                ('contract_count', models.IntegerField(blank=True, default=0)),
                ('university_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='universities.university')),
            ],
        ),
    ]
