# Generated by Django 4.1.6 on 2023-05-08 09:23

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.ImageField(null=True, upload_to='User-badges/')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, null=True, upload_to=user.models.User.nameFile, verbose_name='Image:')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('birthday', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('ball', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('coins', models.DecimalField(decimal_places=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('badge', models.ManyToManyField(blank=True, to='user.badge')),
                ('followers', models.ManyToManyField(blank=True, related_name='Followers', to='user.user')),
                ('following', models.ManyToManyField(blank=True, related_name='Following', to='user.user')),
            ],
        ),
    ]
