# Generated by Django 4.1.5 on 2023-02-11 10:28

from django.db import migrations, models
import django.db.models.deletion
import user.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('image', models.ImageField(blank=True, upload_to=user.models.User.nameFile, verbose_name='Image:')),
                ('name', models.CharField(max_length=30)),
                ('surname', models.CharField(max_length=30)),
                ('phone', models.CharField(blank=True, max_length=30)),
                ('mail', models.CharField(blank=True, max_length=55)),
                ('password', models.CharField(max_length=30)),
                ('birthday', models.CharField(max_length=10)),
                ('region', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=30)),
                ('ball', models.DecimalField(decimal_places=0, default=0, max_digits=16)),
                ('coins', models.DecimalField(decimal_places=0, max_digits=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_online', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Badge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('desc', models.TextField(max_length=500)),
                ('badge_id', models.IntegerField(blank=True)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='user.user')),
            ],
        ),
    ]
