# Generated by Django 4.1.6 on 2023-02-13 10:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='badge',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RemoveField(
            model_name='badge',
            name='badge_id',
        ),
    ]
