# Generated by Django 4.1.6 on 2023-05-15 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.CharField(blank=True, choices=[('E', 'Erkak'), ('A', 'Ayol')], max_length=1, null=True),
        ),
    ]
