# Generated by Django 4.1.6 on 2023-02-14 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_rename_user_id_badge_user_remove_badge_badge_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='user',
        ),
        migrations.AddField(
            model_name='badge',
            name='icon',
            field=models.ImageField(null=True, upload_to='User-badges/'),
        ),
        migrations.AddField(
            model_name='user',
            name='badge',
            field=models.ManyToManyField(blank=True, to='user.badge'),
        ),
    ]
