# Generated by Django 4.1.6 on 2023-05-03 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_remove_user_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_online',
        ),
    ]
