# Generated by Django 4.1.6 on 2023-05-03 16:35

from django.db import migrations, models
import user.models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_remove_user_is_online'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=user.models.User.nameFile, verbose_name='Image:'),
        ),
    ]
