# Generated by Django 4.1.5 on 2023-02-02 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OneToOne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_1', models.CharField(max_length=55)),
                ('user_2', models.CharField(blank=True, max_length=55)),
                ('quiz_count', models.IntegerField()),
                ('science', models.CharField(max_length=33)),
                ('winner', models.CharField(default='', max_length=55)),
                ('correct_1', models.IntegerField(default=0)),
                ('correct_2', models.IntegerField(default=0)),
                ('time', models.IntegerField(default=300)),
                ('code', models.CharField(max_length=6)),
                ('current_question_1', models.IntegerField(default=0)),
                ('current_question_2', models.IntegerField(default=0)),
                ('is_finished', models.BooleanField(default=False)),
            ],
        ),
    ]
