# Generated by Django 4.1.5 on 2023-02-02 16:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='onetoone',
            name='time',
        ),
    ]
