# Generated by Django 4.1.5 on 2023-02-02 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0002_remove_onetoone_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='onetoone',
            name='is_started',
            field=models.BooleanField(default=False),
        ),
    ]
