# Generated by Django 4.1.5 on 2023-02-04 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0003_onetoone_is_started'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetoone',
            name='user_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='onetoone',
            name='user_2',
            field=models.IntegerField(blank=True),
        ),
    ]
