# Generated by Django 4.1.5 on 2023-02-06 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('battle', '0005_alter_onetoone_user_2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetoone',
            name='user_2',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
