# Generated by Django 4.1.6 on 2023-05-09 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0002_contestquiz_alter_contest_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='contestuser',
            name='participation',
            field=models.BooleanField(default=False),
        ),
    ]
