# Generated by Django 4.1.6 on 2023-05-09 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0003_contestuser_participation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contestuser',
            name='ball',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
