# Generated by Django 4.1.6 on 2023-05-15 09:16

import contests.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contests', '0004_alter_contestuser_ball'),
    ]

    operations = [
        migrations.AddField(
            model_name='contest',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=contests.models.Contest.imageName),
        ),
        migrations.AddField(
            model_name='contest',
            name='price',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
