# Generated by Django 4.1.6 on 2023-05-08 09:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuizHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=10)),
                ('ball', models.DecimalField(decimal_places=2, max_digits=5)),
                ('test_count', models.IntegerField()),
                ('time', models.IntegerField(blank=True, null=True)),
                ('ended_time', models.DateTimeField(auto_now=True)),
                ('results', models.JSONField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
