# Generated by Django 4.1.6 on 2023-05-07 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0010_alter_user_image'),
        ('quiz', '0011_alter_quiz_question_image_alter_quiz_question_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ball', models.DecimalField(decimal_places=2, max_digits=3)),
                ('test_count', models.IntegerField()),
                ('ended_time', models.DateTimeField(auto_now=True)),
                ('result', models.JSONField(encoder=False)),
                ('science', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.science')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quiz.subject')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
        ),
    ]
