# Generated by Django 4.1.6 on 2023-05-07 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('histories', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subjecthistory',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='subjecthistory',
            name='ball',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
